//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDoDien.Models.DBConection
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int ID_HoaDon { get; set; }
        public Nullable<int> ID_KH { get; set; }
        public Nullable<int> ID_NV { get; set; }
        public Nullable<int> ID_SP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
